//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        public int KisiID { get; set; }
        public string KisiAd { get; set; }
        public string KisiSoyad { get; set; }
        public string KisiTC { get; set; }
        public string KisiTel { get; set; }
        public string KisiCinsiyet { get; set; }
        public Nullable<System.DateTime> KisiDogumTarihi { get; set; }
        public string KisiDogumYeri { get; set; }
    }
}
